version: '3.2'

volumes:
  vhost-configurations: {}
  ssl-certificates: {}
  html: {}

networks:
  global-nginx-proxy-net:
    external: true

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - vhost-configurations:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ssl-certificates:/etc/nginx/certs
      - ./uploadlimit.conf:/etc/nginx/conf.d/uploadlimit.conf:ro
    restart: always
    networks:
      - global-nginx-proxy-net

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ssl-certificates:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost-configurations:/etc/nginx/vhost.d
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - global-nginx-proxy-net
